       SUBROUTINE USDFLD(FIELD,STATEV,PNEWDT,DIRECT,T,CELENT,
     1 TIME,DTIME,CMNAME,ORNAME,NFIELD,NSTATV,NOEL,NPT,LAYER,
     2 KSPT,KSTEP,KINC,NDI,NSHR,COORD,JMAC,JMATYP,MATLAYO,LACCFLA)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME,ORNAME
      CHARACTER*3  FLGRAY(15)
      DIMENSION FIELD(NFIELD),STATEV(NSTATV),DIRECT(3,3),
     1 T(3,3),TIME(2)
      DIMENSION ARRAY(15),JARRAY(15),JMAC(*),JMATYP(*),COORD(*)
      DOUBLE PRECISION X,Y,Z,d
	  
	  X=COORD(1)
      Y=COORD(2)
	  Z=COORD(3)
	  
	  IF (KINC .LE. 1) THEN
          d=sqrt(X**2+Y**2+Z**2)
          STATEV(1)=d
      ELSE IF (KINC .GT. 1) THEN
	      STATEV(1)=STATEV(1)
	  END IF

      IF (STATEV(1) .LE. 0.5) THEN
	      FIELD(1)=0
	  ELSE IF (STATEV(1) .GT. 0.5 .AND. STATEV(1) .LE. 1.5) THEN
          FIELD(1)=1
	  ELSE IF (STATEV(1) .GT. 1.5 .AND. STATEV(1) .LE. 2.5) THEN
          FIELD(1)=2
      ELSE	
          FIELD(1)=3	  
	  END IF
	  


      RETURN
      END